version: '3'

services:
  pg:
    image: postgres:16
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - "5431:5432"
    env_file:
      - ../src/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
