version: '3'

services:
  pg:
    image: postgres:16
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - "5431:5432"
    env_file:
      - ../src/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.4
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
  redis_data:
