"""rename place address

Revision ID: e656a8ee9fa0
Revises: bb8387d7e543
Create Date: 2024-08-26 17:46:02.367553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e656a8ee9fa0'
down_revision: Union[str, None] = 'bb8387d7e543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('address', sa.Text(), nullable=False))
    op.drop_column('places', 'address_without_city')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('address_without_city', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('places', 'address')
    # ### end Alembic commands ###
